Type: feat & fix
Descripton: 1: refactor system status collacting code to resolv
performance issue ; 2: fix service
table freezing issue caused by column sort; 3: fix some apps not shown
under "my apps" process view mode

RootCause: 1: Null; 2: when sort by 'startup mode' column, external
process(scripts used to check service state) forked too quickly that
 system cant catch up; 3: original logic only consider apps which have
gui window should be added in "my apps" view

Solution: 1: null; 2: move scripts checking logic into standard alone
logic when initializing list, so sort doesnt rely on dynamic process
fork; 3: apps which have .desktop entry should also be added in the list

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,7 +3,15 @@ set -e
 
 if [ "$1" = configure ]; then
 	if command -v setcap > /dev/null; then
-		setcap cap_net_raw+ep /usr/bin/deepin-system-monitor
+		if setcap cap_net_raw,cap_dac_read_search,cap_sys_ptrace+ep /usr/bin/deepin-system-monitor;then
+			chmod u-s /usr/bin/deepin-system-monitor
+		else
+			echo "Setcap failed, falling back to setuid" >&2
+			chmod u+s /usr/bin/deepin-system-monitor
+		fi
+	else
+		echo "Setcap is not installed, falling back to setuid" >&2
+		chmod u+s /usr/bin/deepin-system-monitor
 	fi  
 fi
 
